version: 1.0.{build}
image: Visual Studio 2017
build:
  project: OpenProtocolInterpreter.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: erKpcJ0tSesz5t1D3O+yey+bzVHvg9nsnIkcG2P4j8Kjr4reZ595/fmODipnwJLr
  skip_symbols: true